export const FETCH_ONECARD_REQUEST = "FETCH_ONECARD_REQUEST";
export const FETCH_ONECARD_SUCCESS = "FETCH_ONECARD_SUCCESS";
export const FETCH_ONECARD_FAILURE = "FETCH_ONECARD_FAILURE";

export const SAVE_ONECARD_REQUEST = "SAVE_ONECARD_REQUEST";
export const SAVE_ONECARD_SUCCESS = "SAVE_ONECARD_SUCCESS";
export const SAVE_ONECARD_FAILURE = "SAVE_ONECARD_FAILURE";
